Spark models
FismanMaxim/MiptProject pull request #1
Opened 2023-11-20 13:39 UTC by FismanMaxim

Java spark entities, their controllers and services, Spark backend.

2023-11-29 11:31 UTC, IgorShishkin12 requested changes
все хорошо, но чего-то не хватает

2023-11-29 11:31 UTC, IgorShishkin12 commented on src/test/java/Entities/CompanyTest.java
> +package Entities;
можно и по-больше тестов написать!

2023-11-29 11:31 UTC, IgorShishkin12 commented on src/test/java/EntitiesControllers/CompanyControllerTest.java
> +    }
ненужные методы, один тест

2023-11-29 11:31 UTC, IgorShishkin12 commented on src/test/java/EntitiesControllers/CompanyControllerTest.java
> +        assertEquals(200, response.statusCode());
можно написать тесты, когда что-то идет не так

2023-11-29 11:31 UTC, IgorShishkin12 commented on src/test/java/EntitiesControllers/CompanyControllerTest.java
> +        service.awaitInitialization();
можно вынести в beforeEach

2023-12-02 13:14 UTC, DmitryDos approved these changes

2023-12-02 15:14 UTC, merged